# Generated by Django 2.2 on 2020-10-05 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('message', models.CharField(max_length=200, verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='消息是否已读取')),
                ('receiver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收方的用户名称')),
                ('sender_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='发出方的用户名称')),
            ],
            options={
                'verbose_name': '消息记录',
                'verbose_name_plural': '消息记录',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupOrg', verbose_name='已加入队伍的名称')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户的名称')),
            ],
            options={
                'verbose_name': '组队情况',
                'verbose_name_plural': '组队情况',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('comments', models.CharField(max_length=200, verbose_name='评论内容')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupOrg', verbose_name='被评论队伍的名称')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户的名称')),
            ],
            options={
                'verbose_name': '队伍评论',
                'verbose_name_plural': '队伍评论',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupOrg', verbose_name='申请加入队伍的名称')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户的名称')),
            ],
            options={
                'verbose_name': '组队申请',
                'verbose_name_plural': '组队申请',
            },
        ),
    ]
