# Generated by Django 2.2 on 2020-11-21 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_auto_20201121_1139'),
        ('operations', '0001_initial'),
        ('courses', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名称'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='receiver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收方的用户名称'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='发出方的用户名称'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupOrg', verbose_name='已加入队伍的名称'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户的名称'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='所在课程的名称'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名称'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupOrg', verbose_name='被评论队伍的名称'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户的名称'),
        ),
        migrations.AddField(
            model_name='userask',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupOrg', verbose_name='申请加入队伍的名称'),
        ),
        migrations.AddField(
            model_name='userask',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户的名称'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='被评论项目的名称'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户的名称'),
        ),
    ]
