# Generated by Django 2.2 on 2020-10-06 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lab', models.CharField(max_length=1, verbose_name='实验班名称')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Course', verbose_name='所在课程的名称')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名称')),
            ],
            options={
                'verbose_name': '组队申请',
                'verbose_name_plural': '组队申请',
            },
        ),
    ]
