# Generated by Django 2.2 on 2020-10-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_usercourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '课程名单', 'verbose_name_plural': '课程名单'},
        ),
    ]
