# Generated by Django 2.2 on 2020-10-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20201006_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='所在课程的名称'),
        ),
    ]
