# Generated by Django 2.2 on 2020-10-08 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_auto_20201006_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('tag', models.CharField(max_length=50, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签清单',
                'verbose_name_plural': '标签清单',
            },
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '课程清单', 'verbose_name_plural': '课程清单'},
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Tag', verbose_name='标签')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名称')),
            ],
            options={
                'verbose_name': '用户标签',
                'verbose_name_plural': '用户标签',
            },
        ),
    ]
