# Generated by Django 2.2.17 on 2020-11-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201006_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='head_image/%Y/default.jpg', upload_to='head_image/%Y', verbose_name='头像'),
        ),
    ]
