# Generated by Django 2.2 on 2020-11-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='队伍名称')),
                ('members', models.IntegerField(verbose_name='成员上限')),
                ('detail', models.TextField(verbose_name='队伍详情')),
            ],
            options={
                'verbose_name': '队伍信息',
                'verbose_name_plural': '队伍信息',
            },
        ),
    ]
