# Generated by Django 2.2 on 2020-10-05 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=50, verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='GroupOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='队伍名称')),
                ('members_existing', models.IntegerField(verbose_name='已有成员')),
                ('members_wanted', models.IntegerField(verbose_name='招募成员')),
                ('detail', models.TextField(verbose_name='队伍详情')),
                ('captain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='队长名称')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Course', verbose_name='相应课程')),
            ],
            options={
                'verbose_name': '队伍信息',
                'verbose_name_plural': '队伍信息',
            },
        ),
    ]
