# Generated by Django 2.2 on 2020-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouporg',
            name='members_existing',
        ),
        migrations.AlterField(
            model_name='grouporg',
            name='members_wanted',
            field=models.IntegerField(verbose_name='成员上限'),
        ),
    ]
