# Generated by Django 2.2 on 2020-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20201121_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporg',
            name='group_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='队伍名称'),
        ),
    ]
