# Generated by Django 2.2 on 2020-10-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20201006_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouporg',
            old_name='members_wanted',
            new_name='members',
        ),
    ]
