# Generated by Django 2.2 on 2020-10-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20201006_2126'),
        ('groups', '0003_auto_20201006_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporg',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='相应课程'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
