# Generated by Django 2.2 on 2020-10-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20201006_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouporg',
            name='course',
        ),
    ]
