# Generated by Django 2.2 on 2020-10-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('groups', '0005_remove_grouporg_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporg',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='相应项目'),
        ),
    ]
